<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyKaraoke" Class="QLKaraokeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MINHTAM\SQLEXPRESS;Initial Catalog=QuanLyKaraoke;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QuanLyKaraokeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BANGGIA_MH" Member="BANGGIA_MHs">
    <Type Name="BANGGIA_MH">
      <Column Name="MAMATHANG" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYCAPNHAT_GIAMH" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GIABAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="MATHANG_BANGGIA_MH" Member="MATHANG" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="MATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRANGBI_THIETBI" Member="TRANGBI_THIETBIs">
    <Type Name="TRANGBI_THIETBI">
      <Column Name="MATBITB" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="NGAYTB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TRANGBI_THIETBI_CHITIET_TRANGBI" Member="CHITIET_TRANGBIs" ThisKey="MATBITB" OtherKey="MATBITB" Type="CHITIET_TRANGBI" />
      <Association Name="PHONG_TRANGBI_THIETBI" Member="PHONG" ThisKey="MAPH" OtherKey="MAPH" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BANGGIACAHAT" Member="BANGGIACAHATs">
    <Type Name="BANGGIACAHAT">
      <Column Name="NCN_GIA" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHUNGGIO" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHUNGGIO_BANGGIACAHAT" Member="KHUNGGIO" ThisKey="MAKHUNGGIO" OtherKey="MAKHUNGGIO" Type="KHUNGGIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIET_DICHVU" Member="CHITIET_DICHVUs">
    <Type Name="CHITIET_DICHVU">
      <Column Name="MAPH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHIEUCAHAT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMATHANG" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHITIET_PHIEUCAHAT_CHITIET_DICHVU" Member="CHITIET_PHIEUCAHAT" ThisKey="MAPH,MAPHIEUCAHAT" OtherKey="MAPH,MAPHIEUCAHAT" Type="CHITIET_PHIEUCAHAT" IsForeignKey="true" />
      <Association Name="MATHANG_CHITIET_DICHVU" Member="MATHANG" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="MATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIET_PHIEUCAHAT" Member="CHITIET_PHIEUCAHATs">
    <Type Name="CHITIET_PHIEUCAHAT">
      <Column Name="MAPH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHIEUCAHAT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GIOBD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOKT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CHITIET_PHIEUCAHAT_CHITIET_DICHVU" Member="CHITIET_DICHVUs" ThisKey="MAPH,MAPHIEUCAHAT" OtherKey="MAPH,MAPHIEUCAHAT" Type="CHITIET_DICHVU" />
      <Association Name="CHITIET_PHIEUCAHAT_CHITIETGIOCAHAT" Member="CHITIETGIOCAHATs" ThisKey="MAPH,MAPHIEUCAHAT" OtherKey="MAPH,MAPHIEUCAHAT" Type="CHITIETGIOCAHAT" />
      <Association Name="PHIEUCAHAT_CHITIET_PHIEUCAHAT" Member="PHIEUCAHAT" ThisKey="MAPHIEUCAHAT" OtherKey="MAPHIEUCAHAT" Type="PHIEUCAHAT" IsForeignKey="true" />
      <Association Name="PHONG_CHITIET_PHIEUCAHAT" Member="PHONG" ThisKey="MAPH" OtherKey="MAPH" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIET_TRANGBI" Member="CHITIET_TRANGBIs">
    <Type Name="CHITIET_TRANGBI">
      <Column Name="MATBITB" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMATHANG" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONGTB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TRANGBI_THIETBI_CHITIET_TRANGBI" Member="TRANGBI_THIETBI" ThisKey="MATBITB" OtherKey="MATBITB" Type="TRANGBI_THIETBI" IsForeignKey="true" />
      <Association Name="MATHANG_CHITIET_TRANGBI" Member="MATHANG" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="MATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETGIOCAHAT" Member="CHITIETGIOCAHATs">
    <Type Name="CHITIETGIOCAHAT">
      <Column Name="MAPH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHIEUCAHAT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHUNGGIO" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CHITIET_PHIEUCAHAT_CHITIETGIOCAHAT" Member="CHITIET_PHIEUCAHAT" ThisKey="MAPH,MAPHIEUCAHAT" OtherKey="MAPH,MAPHIEUCAHAT" Type="CHITIET_PHIEUCAHAT" IsForeignKey="true" />
      <Association Name="KHUNGGIO_CHITIETGIOCAHAT" Member="KHUNGGIO" ThisKey="MAKHUNGGIO" OtherKey="MAKHUNGGIO" Type="KHUNGGIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETNHAPMATHANG" Member="CHITIETNHAPMATHANGs">
    <Type Name="CHITIETNHAPMATHANG">
      <Column Name="MACTNH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMATHANG" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MATC" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="MATHANG_CHITIETNHAPMATHANG" Member="MATHANG" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="MATHANG" IsForeignKey="true" />
      <Association Name="PHIEUTHUCHI_CHITIETNHAPMATHANG" Member="PHIEUTHUCHI" ThisKey="MATC" OtherKey="MATC" Type="PHIEUTHUCHI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HESOKHACHHANG" Member="HESOKHACHHANGs">
    <Type Name="HESOKHACHHANG">
      <Column Name="NCN_HSKH" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIKH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="HESO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LOAIKHACHANG_HESOKHACHHANG" Member="LOAIKHACHANG" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="LOAIKHACHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HESOPHONG" Member="HESOPHONGs">
    <Type Name="HESOPHONG">
      <Column Name="NGAYCAPNHAT" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="HESO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LOAIPHONG_HESOPHONG" Member="LOAIPHONG" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAIPHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIKH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_PHIEUCAHAT" Member="PHIEUCAHATs" ThisKey="MAKH" OtherKey="MAKH" Type="PHIEUCAHAT" />
      <Association Name="KHACHHANG_PHIEUDATPHONG" Member="PHIEUDATPHONGs" ThisKey="MAKH" OtherKey="MAKH" Type="PHIEUDATPHONG" />
      <Association Name="LOAIKHACHANG_KHACHHANG" Member="LOAIKHACHANG" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="LOAIKHACHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUNGGIO" Member="KHUNGGIOs">
    <Type Name="KHUNGGIO">
      <Column Name="MAKHUNGGIO" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GIOBD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOKT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KHUNGGIO_BANGGIACAHAT" Member="BANGGIACAHATs" ThisKey="MAKHUNGGIO" OtherKey="MAKHUNGGIO" Type="BANGGIACAHAT" />
      <Association Name="KHUNGGIO_CHITIETGIOCAHAT" Member="CHITIETGIOCAHATs" ThisKey="MAKHUNGGIO" OtherKey="MAKHUNGGIO" Type="CHITIETGIOCAHAT" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIKHACHANG" Member="LOAIKHACHANGs">
    <Type Name="LOAIKHACHANG">
      <Column Name="MALOAIKH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="LOAIKHACHANG_HESOKHACHHANG" Member="HESOKHACHHANGs" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="HESOKHACHHANG" />
      <Association Name="LOAIKHACHANG_KHACHHANG" Member="KHACHHANGs" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="KHACHHANG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIMH" Member="LOAIMHs">
    <Type Name="LOAIMH">
      <Column Name="MALOAIMH" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAIMH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOAIMH_MATHANG" Member="MATHANGs" ThisKey="MALOAIMH" OtherKey="MALOAIMH" Type="MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAI" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="LOAIPHONG_HESOPHONG" Member="HESOPHONGs" ThisKey="MALOAI" OtherKey="MALOAI" Type="HESOPHONG" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAI" OtherKey="MALOAI" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.MANHINH" Member="MANHINHs">
    <Type Name="MANHINH">
      <Column Name="MAMH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMANHINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="PHANQUYENs" ThisKey="MAMH" OtherKey="MAMH" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.MATHANG" Member="MATHANGs">
    <Type Name="MATHANG">
      <Column Name="MAMATHANG" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIMH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENMATHANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONGMH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONGMHTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LOAIHANG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MATHANG_BANGGIA_MH" Member="BANGGIA_MHs" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="BANGGIA_MH" />
      <Association Name="MATHANG_CHITIET_DICHVU" Member="CHITIET_DICHVUs" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="CHITIET_DICHVU" />
      <Association Name="MATHANG_CHITIET_TRANGBI" Member="CHITIET_TRANGBIs" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="CHITIET_TRANGBI" />
      <Association Name="MATHANG_CHITIETNHAPMATHANG" Member="CHITIETNHAPMATHANGs" ThisKey="MAMATHANG" OtherKey="MAMATHANG" Type="CHITIETNHAPMATHANG" />
      <Association Name="LOAIMH_MATHANG" Member="LOAIMH" ThisKey="MALOAIMH" OtherKey="MALOAIMH" Type="LOAIMH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="Char(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="TINHTRANG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NGUOIDUNG_NGUOIDUNG_NHOMNGUOIDUNG" Member="NGUOIDUNG_NHOMNGUOIDUNGs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="NGUOIDUNG_NHOMNGUOIDUNG" />
      <Association Name="NHANVIEN_NGUOIDUNG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG_NHOMNGUOIDUNG" Member="NGUOIDUNG_NHOMNGUOIDUNGs">
    <Type Name="NGUOIDUNG_NHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDANGNHAP" Type="System.String" DbType="Char(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NGUOIDUNG_NGUOIDUNG_NHOMNGUOIDUNG" Member="NGUOIDUNG" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="NHOMNGUOIDUNG_NGUOIDUNG_NHOMNGUOIDUNG" Member="NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QUEQUAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="NHANVIEN_NGUOIDUNG" Member="NGUOIDUNGs" ThisKey="MANV" OtherKey="MANV" Type="NGUOIDUNG" />
      <Association Name="NHANVIEN_PHIEUCAHAT" Member="PHIEUCAHATs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUCAHAT" />
      <Association Name="NHANVIEN_PHIEUDATPHONG" Member="PHIEUDATPHONGs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUDATPHONG" />
      <Association Name="NHANVIEN_PHIEUTHUCHI" Member="PHIEUTHUCHIs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUTHUCHI" />
    </Type>
  </Table>
  <Table Name="dbo.NHOMNGUOIDUNG" Member="NHOMNGUOIDUNGs">
    <Type Name="NHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="NHOMNGUOIDUNG_NGUOIDUNG_NHOMNGUOIDUNG" Member="NGUOIDUNG_NHOMNGUOIDUNGs" ThisKey="MANHOM" OtherKey="MANHOM" Type="NGUOIDUNG_NHOMNGUOIDUNG" />
      <Association Name="NHOMNGUOIDUNG_PHANQUYEN" Member="PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MANHOM" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="MANHINH" ThisKey="MAMH" OtherKey="MAMH" Type="MANHINH" IsForeignKey="true" />
      <Association Name="NHOMNGUOIDUNG_PHANQUYEN" Member="NHOMNGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUCAHAT" Member="PHIEUCAHATs">
    <Type Name="PHIEUCAHAT">
      <Column Name="MAPHIEUCAHAT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATC" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MAPHIEUDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="NGAYLAPPHIEUCH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PHIEUCAHAT_CHITIET_PHIEUCAHAT" Member="CHITIET_PHIEUCAHATs" ThisKey="MAPHIEUCAHAT" OtherKey="MAPHIEUCAHAT" Type="CHITIET_PHIEUCAHAT" />
      <Association Name="PHIEUCAHAT_PHIEUDATPHONG" Member="PHIEUDATPHONGs" ThisKey="MAPHIEUCAHAT" OtherKey="MAPHIEUCAHAT" Type="PHIEUDATPHONG" />
      <Association Name="KHACHHANG_PHIEUCAHAT" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUCAHAT" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUDATPHONG_PHIEUCAHAT" Member="PHIEUDATPHONG" ThisKey="MAPHIEUDH" OtherKey="MAPHIEUDH" Type="PHIEUDATPHONG" IsForeignKey="true" />
      <Association Name="PHIEUTHUCHI_PHIEUCAHAT" Member="PHIEUTHUCHI" ThisKey="MATC" OtherKey="MATC" Type="PHIEUTHUCHI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUDATPHONG" Member="PHIEUDATPHONGs">
    <Type Name="PHIEUDATPHONG">
      <Column Name="MAPHIEUDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHIEUCAHAT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GIODAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PHIEUDATPHONG_PHIEUCAHAT" Member="PHIEUCAHATs" ThisKey="MAPHIEUDH" OtherKey="MAPHIEUDH" Type="PHIEUCAHAT" />
      <Association Name="KHACHHANG_PHIEUDATPHONG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUDATPHONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUCAHAT_PHIEUDATPHONG" Member="PHIEUCAHAT" ThisKey="MAPHIEUCAHAT" OtherKey="MAPHIEUCAHAT" Type="PHIEUCAHAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUTHUCHI" Member="PHIEUTHUCHIs">
    <Type Name="PHIEUTHUCHI">
      <Column Name="MATC" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MAITC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIENTC" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="NGAYTC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PHIEUTHUCHI_CHITIETNHAPMATHANG" Member="CHITIETNHAPMATHANGs" ThisKey="MATC" OtherKey="MATC" Type="CHITIETNHAPMATHANG" />
      <Association Name="PHIEUTHUCHI_PHIEUCAHAT" Member="PHIEUCAHATs" ThisKey="MATC" OtherKey="MATC" Type="PHIEUCAHAT" />
      <Association Name="NHANVIEN_PHIEUTHUCHI" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="THUCHI_PHIEUTHUCHI" Member="THUCHI" ThisKey="MAITC" OtherKey="MAITC" Type="THUCHI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="TENPH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Association Name="PHONG_TRANGBI_THIETBI" Member="TRANGBI_THIETBIs" ThisKey="MAPH" OtherKey="MAPH" Type="TRANGBI_THIETBI" />
      <Association Name="PHONG_CHITIET_PHIEUCAHAT" Member="CHITIET_PHIEUCAHATs" ThisKey="MAPH" OtherKey="MAPH" Type="CHITIET_PHIEUCAHAT" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAIPHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THUCHI" Member="THUCHIs">
    <Type Name="THUCHI">
      <Column Name="MAITC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LOAITC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="THUCHI_PHIEUTHUCHI" Member="PHIEUTHUCHIs" ThisKey="MAITC" OtherKey="MAITC" Type="PHIEUTHUCHI" />
    </Type>
  </Table>
</Database>